In [1]:
%%shell
set -e

#---------------------------------------------------#
JULIA_VERSION="1.7.1" # any version ≥ 0.7.0
JULIA_PACKAGES="IJulia CSV DataFrames Random Statistics Distributions LinearAlgebra SparseArrays Printf JWAS"  # CSV DataFrames Random Statistics JWAS Distributions LinearAlgebra
JULIA_PACKAGES_IF_GPU=""
JULIA_NUM_THREADS=4
#---------------------------------------------------#

if [ -n "$COLAB_GPU" ] && [ -z `which julia` ]; then
  # Install Julia
  JULIA_VER=`cut -d '.' -f -2 <<< "$JULIA_VERSION"`
  echo "Installing Julia $JULIA_VERSION on the current Colab Runtime..."
  BASE_URL="https://julialang-s3.julialang.org/bin/linux/x64"
  URL="$BASE_URL/$JULIA_VER/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
  wget -nv $URL -O /tmp/julia.tar.gz # -nv means "not verbose"
  tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
  rm /tmp/julia.tar.gz

  # Install Packages
  if [ "$COLAB_GPU" = "1" ]; then
      JULIA_PACKAGES="$JULIA_PACKAGES $JULIA_PACKAGES_IF_GPU"
  fi
  for PKG in `echo $JULIA_PACKAGES`; do
    echo "Installing Julia package $PKG..."
    julia -e 'using Pkg; pkg"add '$PKG'; precompile;"' &> /dev/null
  done

  # Install kernel and rename it to "julia"
  echo "Installing IJulia kernel..."
  julia -e 'using IJulia; IJulia.installkernel("julia", env=Dict(
      "JULIA_NUM_THREADS"=>"'"$JULIA_NUM_THREADS"'"))'
  KERNEL_DIR=`julia -e "using IJulia; print(IJulia.kerneldir())"`
  KERNEL_NAME=`ls -d "$KERNEL_DIR"/julia*`
  mv -f $KERNEL_NAME "$KERNEL_DIR"/julia  

  echo ''
  echo "Successfully installed `julia -v`!"
  echo "Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then"
  echo "jump to the 'Checking the Installation' section."
fi

Unrecognized magic `%%shell`.

Julia does not use the IPython `%magic` syntax.   To interact with the IJulia kernel, use `IJulia.somefunction(...)`, for example.  Julia macros, string macros, and functions can be used to accomplish most of the other functionalities of IPython magics.


In [2]:
versioninfo()

Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 4


In [6]:
M = rand(Binomial(2,0.5),10,20)

10×20 Matrix{Int64}:
 1  1  0  2  0  2  1  0  2  0  1  2  2  1  2  1  1  0  0  1
 0  0  0  0  1  1  0  1  2  2  1  1  0  1  2  1  2  0  1  1
 1  2  0  0  1  1  0  2  2  1  0  0  1  1  1  2  0  1  2  0
 1  1  1  1  0  2  0  2  1  0  1  1  2  2  1  1  1  1  0  0
 1  0  1  2  1  1  1  0  2  0  1  0  1  1  1  1  1  2  0  0
 1  1  0  0  2  0  0  1  2  0  0  1  0  0  2  0  0  1  2  1
 0  1  0  1  1  1  1  2  1  1  2  2  2  1  1  1  2  0  1  2
 1  2  2  2  1  1  2  1  0  2  0  2  2  2  2  1  0  2  1  2
 2  1  1  0  2  1  1  1  1  0  1  0  1  0  2  2  1  0  1  0
 1  1  0  1  1  1  2  0  1  0  1  0  0  1  0  0  0  0  2  2

In [5]:
using Distributions

In [7]:
using SparseArrays, LinearAlgebra
x=[1,1,2,2,2,2,3,3,4,1]
y=[1.1,1.2,1.9,1.2,2.0,1.7,1.0,1.7,1.1,1.7]
n = size(x,1)

10

In [8]:
spzeros(2,2)

2×2 SparseMatrixCSC{Float64, Int64} with 0 stored entries:
  ⋅    ⋅ 
  ⋅    ⋅ 

In [11]:

for i=1:size(u,1)
    result[i] = u[i] + v[i]
end
[u v result]

LoadError: ignored

In [12]:
result = zero(u)
for i=1:size(u,1)
    result[i] = u[i] + v[i]
end
[u v result]

LoadError: ignored

In [13]:
r = range(0, step=0.1, stop=1)

0.0:0.1:1.0

In [14]:
# This works too

r = 0:0.1:1

0.0:0.1:1.0

In [15]:
sin.(r)

11-element Vector{Float64}:
 0.0
 0.09983341664682815
 0.19866933079506122
 0.29552020666133955
 0.3894183423086505
 0.479425538604203
 0.5646424733950354
 0.644217687237691
 0.7173560908995228
 0.7833269096274834
 0.8414709848078965

In [20]:
map(sin,r)

11-element Vector{Float64}:
 0.0
 0.09983341664682815
 0.19866933079506122
 0.29552020666133955
 0.3894183423086505
 0.479425538604203
 0.5646424733950354
 0.644217687237691
 0.7173560908995228
 0.7833269096274834
 0.8414709848078965

In [22]:
# type of M
typeof(M)

Matrix{Int64} (alias for Array{Int64, 2})

In [23]:
# type of v
typeof(v)

LoadError: ignored

In [24]:
# Example
mutable struct BankAccount
    accountNumber::Int64
    firstName::String
    lastName::String
    balance::Float64
end

In [26]:
fieldnames(BankAccount)

(:accountNumber, :firstName, :lastName, :balance)

In [27]:
BankAccount.types

svec(Int64, String, String, Float64)

In [28]:
a1 = BankAccount(1234,"Tom","Smith",1000.0)
a2 = BankAccount(4321,"Jim","Shanks",500.0)
a3 = BankAccount(9321,"Scott","Williams",500.0)

BankAccount(9321, "Scott", "Williams", 500.0)

In [29]:
a1.balance

1000.0

In [30]:
# can modify fields of mutable structs
a1.balance = 2000.50

2000.5

In [31]:
a2.balance

500.0

In [32]:
a2.firstName

"Jim"

In [33]:
#= 
d is an empty dictionary that can store "BackAccounts" 
with an interger key (i.e., with the account number as the key)
=#

d = Dict{Int64,BankAccount}()

Dict{Int64, BankAccount}()

In [34]:
@show(a1)

a1 = BankAccount(1234, "Tom", "Smith", 2000.5)


BankAccount(1234, "Tom", "Smith", 2000.5)

In [35]:
d[a1.accountNumber] = a1
d

Dict{Int64, BankAccount} with 1 entry:
  1234 => BankAccount(1234, "Tom", "Smith", 2000.5)

In [36]:
function addVectors(u,v)
    if size(u,1) != size(v,1)
        println("The size of u (= $(size(u,1))) is not equal to the size of v (= $(size(v,1))) ")
        return []
    end
    result = zero(u)
    for i=1:size(u,1)
        result[i] = u[i] + v[i]
    end
    return result
end

addVectors (generic function with 1 method)

In [37]:
function name_of_fcn(a,b,c)

end

name_of_fcn (generic function with 1 method)

In [39]:
function name_of_fcn(a; c=1)
      a+c
end

name_of_fcn (generic function with 3 methods)

In [41]:
name_of_fcn(2,c=100)

102

In [43]:
using Printf # needed for formatted print commands

In [44]:
A = randn(5,3)

5×3 Matrix{Float64}:
 -0.109315    0.454418  -0.145999
  1.37484    -1.34681   -0.349873
 -0.0700134   0.826333   1.98259
 -0.352404    0.607113  -0.124878
  0.14788     0.897852  -0.885351

In [45]:
out = open("outFile","w")
n,p = size(A)
for j=1:p
    for i=1:n
        @printf(out,"%10.5f ", A[i,j])
    end
    @printf(out,"\n")
end
close(out)

In [46]:
;cat outFile

  -0.10932    1.37484   -0.07001   -0.35240    0.14788 
   0.45442   -1.34681    0.82633    0.60711    0.89785 
  -0.14600   -0.34987    1.98259   -0.12488   -0.88535 
